(function UMDish(name,context,definition,plugins){context[name]=definition.call(context);for(var i=0;i<plugins.length;i++){plugins[i](context[name])}
if(typeof module!=="undefined"&&module.exports){module.exports=context[name]}else if(typeof define==="function"&&define.amd){define(function reference(){return context[name]})}})("Primus",this||{},function wrapper(){var define,module,exports,Primus=(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(_dereq_,module,exports){'use strict';module.exports=function demolish(keys,options){var split=/[, ]+/;options=options||{};keys=keys||[];if('string'===typeof keys)keys=keys.split(split);function run(key,selfie){if(!options[key])return;if('string'===typeof options[key])options[key]=options[key].split(split);if('function'===typeof options[key])return options[key].call(selfie);for(var i=0,type,what;i<options[key].length;i++){what=options[key][i];type=typeof what;if('function'===type){what.call(selfie)}else if('string'===type&&'function'===typeof selfie[what]){selfie[what]()}}}
return function destroy(){var selfie=this,i=0,prop;if(selfie[keys[0]]===null)return!1;run('before',selfie);for(;i<keys.length;i++){prop=keys[i];if(selfie[prop]){if('function'===typeof selfie[prop].destroy)selfie[prop].destroy();selfie[prop]=null}}
if(selfie.emit)selfie.emit('destroy');run('after',selfie);return!0}}},{}],2:[function(_dereq_,module,exports){'use strict';module.exports=function emits(){var self=this,parser;for(var i=0,l=arguments.length,args=new Array(l);i<l;i++){args[i]=arguments[i]}
if('function'!==typeof args[args.length-1])return function emitter(){for(var i=0,l=arguments.length,arg=new Array(l);i<l;i++){arg[i]=arguments[i]}
return self.emit.apply(self,args.concat(arg))};parser=args.pop();return function emitter(){for(var i=0,l=arguments.length,arg=new Array(l+1);i<l;i++){arg[i+1]=arguments[i]}
arg[0]=function next(err,returned){if(err)return self.emit('error',err);arg=returned===undefined?arg.slice(1):returned===null?[]:returned;self.emit.apply(self,args.concat(arg))};parser.apply(self,arg);return!0}}},{}],3:[function(_dereq_,module,exports){'use strict';var has=Object.prototype.hasOwnProperty,prefix='~';function Events(){}
if(Object.create){Events.prototype=Object.create(null);if(!new Events().__proto__)prefix=!1}
function EE(fn,context,once){this.fn=fn;this.context=context;this.once=once||!1}
function addListener(emitter,event,fn,context,once){if(typeof fn!=='function'){throw new TypeError('The listener must be a function')}
var listener=new EE(fn,context||emitter,once),evt=prefix?prefix+event:event;if(!emitter._events[evt])emitter._events[evt]=listener,emitter._eventsCount++;else if(!emitter._events[evt].fn)emitter._events[evt].push(listener);else emitter._events[evt]=[emitter._events[evt],listener];return emitter}
function clearEvent(emitter,evt){if(--emitter._eventsCount===0)emitter._events=new Events();else delete emitter._events[evt]}
function EventEmitter(){this._events=new Events();this._eventsCount=0}
EventEmitter.prototype.eventNames=function eventNames(){var names=[],events,name;if(this._eventsCount===0)return names;for(name in(events=this._events)){if(has.call(events,name))names.push(prefix?name.slice(1):name)}
if(Object.getOwnPropertySymbols){return names.concat(Object.getOwnPropertySymbols(events))}
return names};EventEmitter.prototype.listeners=function listeners(event){var evt=prefix?prefix+event:event,handlers=this._events[evt];if(!handlers)return[];if(handlers.fn)return[handlers.fn];for(var i=0,l=handlers.length,ee=new Array(l);i<l;i++){ee[i]=handlers[i].fn}
return ee};EventEmitter.prototype.listenerCount=function listenerCount(event){var evt=prefix?prefix+event:event,listeners=this._events[evt];if(!listeners)return 0;if(listeners.fn)return 1;return listeners.length};EventEmitter.prototype.emit=function emit(event,a1,a2,a3,a4,a5){var evt=prefix?prefix+event:event;if(!this._events[evt])return!1;var listeners=this._events[evt],len=arguments.length,args,i;if(listeners.fn){if(listeners.once)this.removeListener(event,listeners.fn,undefined,!0);switch(len){case 1:return listeners.fn.call(listeners.context),!0;case 2:return listeners.fn.call(listeners.context,a1),!0;case 3:return listeners.fn.call(listeners.context,a1,a2),!0;case 4:return listeners.fn.call(listeners.context,a1,a2,a3),!0;case 5:return listeners.fn.call(listeners.context,a1,a2,a3,a4),!0;case 6:return listeners.fn.call(listeners.context,a1,a2,a3,a4,a5),!0}
for(i=1,args=new Array(len-1);i<len;i++){args[i-1]=arguments[i]}
listeners.fn.apply(listeners.context,args)}else{var length=listeners.length,j;for(i=0;i<length;i++){if(listeners[i].once)this.removeListener(event,listeners[i].fn,undefined,!0);switch(len){case 1:listeners[i].fn.call(listeners[i].context);break;case 2:listeners[i].fn.call(listeners[i].context,a1);break;case 3:listeners[i].fn.call(listeners[i].context,a1,a2);break;case 4:listeners[i].fn.call(listeners[i].context,a1,a2,a3);break;default:if(!args)for(j=1,args=new Array(len-1);j<len;j++){args[j-1]=arguments[j]}
listeners[i].fn.apply(listeners[i].context,args)}}}
return!0};EventEmitter.prototype.on=function on(event,fn,context){return addListener(this,event,fn,context,!1)};EventEmitter.prototype.once=function once(event,fn,context){return addListener(this,event,fn,context,!0)};EventEmitter.prototype.removeListener=function removeListener(event,fn,context,once){var evt=prefix?prefix+event:event;if(!this._events[evt])return this;if(!fn){clearEvent(this,evt);return this}
var listeners=this._events[evt];if(listeners.fn){if(listeners.fn===fn&&(!once||listeners.once)&&(!context||listeners.context===context)){clearEvent(this,evt)}}else{for(var i=0,events=[],length=listeners.length;i<length;i++){if(listeners[i].fn!==fn||(once&&!listeners[i].once)||(context&&listeners[i].context!==context)){events.push(listeners[i])}}
if(events.length)this._events[evt]=events.length===1?events[0]:events;else clearEvent(this,evt)}
return this};EventEmitter.prototype.removeAllListeners=function removeAllListeners(event){var evt;if(event){evt=prefix?prefix+event:event;if(this._events[evt])clearEvent(this,evt)}else{this._events=new Events();this._eventsCount=0}
return this};EventEmitter.prototype.off=EventEmitter.prototype.removeListener;EventEmitter.prototype.addListener=EventEmitter.prototype.on;EventEmitter.prefixed=prefix;EventEmitter.EventEmitter=EventEmitter;if('undefined'!==typeof module){module.exports=EventEmitter}},{}],4:[function(_dereq_,module,exports){if(typeof Object.create==='function'){module.exports=function inherits(ctor,superCtor){ctor.super_=superCtor
ctor.prototype=Object.create(superCtor.prototype,{constructor:{value:ctor,enumerable:!1,writable:!0,configurable:!0}})}}else{module.exports=function inherits(ctor,superCtor){ctor.super_=superCtor
var TempCtor=function(){}
TempCtor.prototype=superCtor.prototype
ctor.prototype=new TempCtor()
ctor.prototype.constructor=ctor}}},{}],5:[function(_dereq_,module,exports){'use strict';var regex=new RegExp('^((?:\\d+)?\\.?\\d+) *('+['milliseconds?','msecs?','ms','seconds?','secs?','s','minutes?','mins?','m','hours?','hrs?','h','days?','d','weeks?','wks?','w','years?','yrs?','y'].join('|')+')?$','i');var second=1000,minute=second*60,hour=minute*60,day=hour*24,week=day*7,year=day*365;module.exports=function millisecond(ms){var type=typeof ms,amount,match;if('number'===type)return ms;else if('string'!==type||'0'===ms||!ms)return 0;else if(+ms)return+ms;if(ms.length>10000||!(match=regex.exec(ms)))return 0;amount=parseFloat(match[1]);switch(match[2].toLowerCase()){case 'years':case 'year':case 'yrs':case 'yr':case 'y':return amount*year;case 'weeks':case 'week':case 'wks':case 'wk':case 'w':return amount*week;case 'days':case 'day':case 'd':return amount*day;case 'hours':case 'hour':case 'hrs':case 'hr':case 'h':return amount*hour;case 'minutes':case 'minute':case 'mins':case 'min':case 'm':return amount*minute;case 'seconds':case 'second':case 'secs':case 'sec':case 's':return amount*second;default:return amount}}},{}],6:[function(_dereq_,module,exports){'use strict';module.exports=function one(fn){var called=0,value;function onetime(){if(called)return value;called=1;value=fn.apply(this,arguments);fn=null;return value}
onetime.displayName=fn.displayName||fn.name||onetime.displayName||onetime.name;return onetime}},{}],7:[function(_dereq_,module,exports){'use strict';var has=Object.prototype.hasOwnProperty;function decode(input){return decodeURIComponent(input.replace(/\+/g,' '))}
function querystring(query){var parser=/([^=?&]+)=?([^&]*)/g,result={},part;while(part=parser.exec(query)){var key=decode(part[1]),value=decode(part[2]);if(key in result)continue;result[key]=value}
return result}
function querystringify(obj,prefix){prefix=prefix||'';var pairs=[];if('string'!==typeof prefix)prefix='?';for(var key in obj){if(has.call(obj,key)){pairs.push(encodeURIComponent(key)+'='+encodeURIComponent(obj[key]))}}
return pairs.length?prefix+pairs.join('&'):''}
exports.stringify=querystringify;exports.parse=querystring},{}],8:[function(_dereq_,module,exports){'use strict';var EventEmitter=_dereq_('eventemitter3'),millisecond=_dereq_('millisecond'),destroy=_dereq_('demolish'),Tick=_dereq_('tick-tock'),one=_dereq_('one-time');function defaults(name,selfie,opts){return millisecond(name in opts?opts[name]:(name in selfie?selfie[name]:Recovery[name]))}
function Recovery(options){var recovery=this;if(!(recovery instanceof Recovery))return new Recovery(options);options=options||{};recovery.attempt=null;recovery._fn=null;recovery['reconnect timeout']=defaults('reconnect timeout',recovery,options);recovery.retries=defaults('retries',recovery,options);recovery.factor=defaults('factor',recovery,options);recovery.max=defaults('max',recovery,options);recovery.min=defaults('min',recovery,options);recovery.timers=new Tick(recovery)}
Recovery.prototype=new EventEmitter();Recovery.prototype.constructor=Recovery;Recovery['reconnect timeout']='30 seconds';Recovery.max=Infinity;Recovery.min='500 ms';Recovery.retries=10;Recovery.factor=2;Recovery.prototype.reconnect=function reconnect(){var recovery=this;return recovery.backoff(function backedoff(err,opts){opts.duration=(+new Date())-opts.start;if(err)return recovery.emit('reconnect failed',err,opts);recovery.emit('reconnected',opts)},recovery.attempt)};Recovery.prototype.backoff=function backoff(fn,opts){var recovery=this;opts=opts||recovery.attempt||{};if(opts.backoff)return recovery;opts['reconnect timeout']=defaults('reconnect timeout',recovery,opts);opts.retries=defaults('retries',recovery,opts);opts.factor=defaults('factor',recovery,opts);opts.max=defaults('max',recovery,opts);opts.min=defaults('min',recovery,opts);opts.start=+opts.start||+new Date();opts.duration=+opts.duration||0;opts.attempt=+opts.attempt||0;if(opts.attempt===opts.retries){fn.call(recovery,new Error('Unable to recover'),opts);return recovery}
opts.backoff=!0;opts.attempt++;recovery.attempt=opts;opts.scheduled=opts.attempt!==1?Math.min(Math.round((Math.random()+1)*opts.min*Math.pow(opts.factor,opts.attempt-1)),opts.max):opts.min;recovery.timers.setTimeout('reconnect',function delay(){opts.duration=(+new Date())-opts.start;opts.backoff=!1;recovery.timers.clear('reconnect, timeout');var connect=recovery._fn=one(function connect(err){recovery.reset();if(err)return recovery.backoff(fn,opts);fn.call(recovery,undefined,opts)});recovery.emit('reconnect',opts,connect);recovery.timers.setTimeout('timeout',function timeout(){var err=new Error('Failed to reconnect in a timely manner');opts.duration=(+new Date())-opts.start;recovery.emit('reconnect timeout',err,opts);connect(err)},opts['reconnect timeout'])},opts.scheduled);recovery.emit('reconnect scheduled',opts);return recovery};Recovery.prototype.reconnecting=function reconnecting(){return!!this.attempt};Recovery.prototype.reconnected=function reconnected(err){if(this._fn)this._fn(err);return this};Recovery.prototype.reset=function reset(){this._fn=this.attempt=null;this.timers.clear('reconnect, timeout');return this};Recovery.prototype.destroy=destroy('timers attempt _fn');module.exports=Recovery},{"demolish":1,"eventemitter3":9,"millisecond":5,"one-time":6,"tick-tock":11}],9:[function(_dereq_,module,exports){'use strict';var prefix=typeof Object.create!=='function'?'~':!1;function EE(fn,context,once){this.fn=fn;this.context=context;this.once=once||!1}
function EventEmitter(){}
EventEmitter.prototype._events=undefined;EventEmitter.prototype.listeners=function listeners(event,exists){var evt=prefix?prefix+event:event,available=this._events&&this._events[evt];if(exists)return!!available;if(!available)return[];if(available.fn)return[available.fn];for(var i=0,l=available.length,ee=new Array(l);i<l;i++){ee[i]=available[i].fn}
return ee};EventEmitter.prototype.emit=function emit(event,a1,a2,a3,a4,a5){var evt=prefix?prefix+event:event;if(!this._events||!this._events[evt])return!1;var listeners=this._events[evt],len=arguments.length,args,i;if('function'===typeof listeners.fn){if(listeners.once)this.removeListener(event,listeners.fn,undefined,!0);switch(len){case 1:return listeners.fn.call(listeners.context),!0;case 2:return listeners.fn.call(listeners.context,a1),!0;case 3:return listeners.fn.call(listeners.context,a1,a2),!0;case 4:return listeners.fn.call(listeners.context,a1,a2,a3),!0;case 5:return listeners.fn.call(listeners.context,a1,a2,a3,a4),!0;case 6:return listeners.fn.call(listeners.context,a1,a2,a3,a4,a5),!0}
for(i=1,args=new Array(len-1);i<len;i++){args[i-1]=arguments[i]}
listeners.fn.apply(listeners.context,args)}else{var length=listeners.length,j;for(i=0;i<length;i++){if(listeners[i].once)this.removeListener(event,listeners[i].fn,undefined,!0);switch(len){case 1:listeners[i].fn.call(listeners[i].context);break;case 2:listeners[i].fn.call(listeners[i].context,a1);break;case 3:listeners[i].fn.call(listeners[i].context,a1,a2);break;default:if(!args)for(j=1,args=new Array(len-1);j<len;j++){args[j-1]=arguments[j]}
listeners[i].fn.apply(listeners[i].context,args)}}}
return!0};EventEmitter.prototype.on=function on(event,fn,context){var listener=new EE(fn,context||this),evt=prefix?prefix+event:event;if(!this._events)this._events=prefix?{}:Object.create(null);if(!this._events[evt])this._events[evt]=listener;else{if(!this._events[evt].fn)this._events[evt].push(listener);else this._events[evt]=[this._events[evt],listener]}
return this};EventEmitter.prototype.once=function once(event,fn,context){var listener=new EE(fn,context||this,!0),evt=prefix?prefix+event:event;if(!this._events)this._events=prefix?{}:Object.create(null);if(!this._events[evt])this._events[evt]=listener;else{if(!this._events[evt].fn)this._events[evt].push(listener);else this._events[evt]=[this._events[evt],listener]}
return this};EventEmitter.prototype.removeListener=function removeListener(event,fn,context,once){var evt=prefix?prefix+event:event;if(!this._events||!this._events[evt])return this;var listeners=this._events[evt],events=[];if(fn){if(listeners.fn){if(listeners.fn!==fn||(once&&!listeners.once)||(context&&listeners.context!==context)){events.push(listeners)}}else{for(var i=0,length=listeners.length;i<length;i++){if(listeners[i].fn!==fn||(once&&!listeners[i].once)||(context&&listeners[i].context!==context)){events.push(listeners[i])}}}}
if(events.length){this._events[evt]=events.length===1?events[0]:events}else{delete this._events[evt]}
return this};EventEmitter.prototype.removeAllListeners=function removeAllListeners(event){if(!this._events)return this;if(event)delete this._events[prefix?prefix+event:event];else this._events=prefix?{}:Object.create(null);return this};EventEmitter.prototype.off=EventEmitter.prototype.removeListener;EventEmitter.prototype.addListener=EventEmitter.prototype.on;EventEmitter.prototype.setMaxListeners=function setMaxListeners(){return this};EventEmitter.prefixed=prefix;if('undefined'!==typeof module){module.exports=EventEmitter}},{}],10:[function(_dereq_,module,exports){'use strict';module.exports=function required(port,protocol){protocol=protocol.split(':')[0];port=+port;if(!port)return!1;switch(protocol){case 'http':case 'ws':return port!==80;case 'https':case 'wss':return port!==443;case 'ftp':return port!==21;case 'gopher':return port!==70;case 'file':return!1}
return port!==0}},{}],11:[function(_dereq_,module,exports){'use strict';var has=Object.prototype.hasOwnProperty,ms=_dereq_('millisecond');function Timer(timer,clear,duration,fn){this.start=+(new Date());this.duration=duration;this.clear=clear;this.timer=timer;this.fns=[fn]}
Timer.prototype.remaining=function remaining(){return this.duration-this.taken()};Timer.prototype.taken=function taken(){return+(new Date())-this.start};function unsetTimeout(id){clearTimeout(id)}
function unsetInterval(id){clearInterval(id)}
function unsetImmediate(id){clearImmediate(id)}
function Tick(context){if(!(this instanceof Tick))return new Tick(context);this.timers={};this.context=context||this}
Tick.prototype.tock=function ticktock(name,clear){var tock=this;return function tickedtock(){if(!(name in tock.timers))return;var timer=tock.timers[name],fns=timer.fns.slice(),l=fns.length,i=0;if(clear)tock.clear(name);else tock.start=+new Date();for(;i<l;i++){fns[i].call(tock.context)}}};Tick.prototype.setTimeout=function timeout(name,fn,time){var tick=this,tock;if(tick.timers[name]){tick.timers[name].fns.push(fn);return tick}
tock=ms(time);tick.timers[name]=new Timer(setTimeout(tick.tock(name,!0),ms(time)),unsetTimeout,tock,fn);return tick};Tick.prototype.setInterval=function interval(name,fn,time){var tick=this,tock;if(tick.timers[name]){tick.timers[name].fns.push(fn);return tick}
tock=ms(time);tick.timers[name]=new Timer(setInterval(tick.tock(name),ms(time)),unsetInterval,tock,fn);return tick};Tick.prototype.setImmediate=function immediate(name,fn){var tick=this;if('function'!==typeof setImmediate)return tick.setTimeout(name,fn,0);if(tick.timers[name]){tick.timers[name].fns.push(fn);return tick}
tick.timers[name]=new Timer(setImmediate(tick.tock(name,!0)),unsetImmediate,0,fn);return tick};Tick.prototype.active=function active(name){return name in this.timers};Tick.prototype.clear=function clear(){var args=arguments.length?arguments:[],tick=this,timer,i,l;if(args.length===1&&'string'===typeof args[0]){args=args[0].split(/[, ]+/)}
if(!args.length){for(timer in tick.timers){if(has.call(tick.timers,timer))args.push(timer)}}
for(i=0,l=args.length;i<l;i++){timer=tick.timers[args[i]];if(!timer)continue;timer.clear(timer.timer);timer.fns=timer.timer=timer.clear=null;delete tick.timers[args[i]]}
return tick};Tick.prototype.adjust=function adjust(name,time){var interval,tick=this,tock=ms(time),timer=tick.timers[name];if(!timer)return tick;interval=timer.clear===unsetInterval;timer.clear(timer.timer);timer.start=+(new Date());timer.duration=tock;timer.timer=(interval?setInterval:setTimeout)(tick.tock(name,!interval),tock);return tick};Tick.prototype.end=Tick.prototype.destroy=function end(){if(!this.context)return!1;this.clear();this.context=this.timers=null;return!0};Tick.Timer=Timer;module.exports=Tick},{"millisecond":5}],12:[function(_dereq_,module,exports){(function(global){'use strict';var required=_dereq_('requires-port'),qs=_dereq_('querystringify'),protocolre=/^([a-z][a-z0-9.+-]*:)?(\/\/)?([\S\s]*)/i,slashes=/^[A-Za-z][A-Za-z0-9+-.]*:\/\//;var rules=[['#','hash'],['?','query'],['/','pathname'],['@','auth',1],[NaN,'host',undefined,1,1],[/:(\d+)$/,'port',undefined,1],[NaN,'hostname',undefined,1,1]];var ignore={hash:1,query:1};function lolcation(loc){loc=loc||global.location||{};var finaldestination={},type=typeof loc,key;if('blob:'===loc.protocol){finaldestination=new URL(unescape(loc.pathname),{})}else if('string'===type){finaldestination=new URL(loc,{});for(key in ignore)delete finaldestination[key]}else if('object'===type){for(key in loc){if(key in ignore)continue;finaldestination[key]=loc[key]}
if(finaldestination.slashes===undefined){finaldestination.slashes=slashes.test(loc.href)}}
return finaldestination}
function extractProtocol(address){var match=protocolre.exec(address);return{protocol:match[1]?match[1].toLowerCase():'',slashes:!!match[2],rest:match[3]}}
function resolve(relative,base){var path=(base||'/').split('/').slice(0,-1).concat(relative.split('/')),i=path.length,last=path[i-1],unshift=!1,up=0;while(i--){if(path[i]==='.'){path.splice(i,1)}else if(path[i]==='..'){path.splice(i,1);up++}else if(up){if(i===0)unshift=!0;path.splice(i,1);up--}}
if(unshift)path.unshift('');if(last==='.'||last==='..')path.push('');return path.join('/')}
function URL(address,location,parser){if(!(this instanceof URL)){return new URL(address,location,parser)}
var relative,extracted,parse,instruction,index,key,instructions=rules.slice(),type=typeof location,url=this,i=0;if('object'!==type&&'string'!==type){parser=location;location=null}
if(parser&&'function'!==typeof parser)parser=qs.parse;location=lolcation(location);extracted=extractProtocol(address||'');relative=!extracted.protocol&&!extracted.slashes;url.slashes=extracted.slashes||relative&&location.slashes;url.protocol=extracted.protocol||location.protocol||'';address=extracted.rest;if(!extracted.slashes)instructions[2]=[/(.*)/,'pathname'];for(;i<instructions.length;i++){instruction=instructions[i];parse=instruction[0];key=instruction[1];if(parse!==parse){url[key]=address}else if('string'===typeof parse){if(~(index=address.indexOf(parse))){if('number'===typeof instruction[2]){url[key]=address.slice(0,index);address=address.slice(index+instruction[2])}else{url[key]=address.slice(index);address=address.slice(0,index)}}}else if((index=parse.exec(address))){url[key]=index[1];address=address.slice(0,index.index)}
url[key]=url[key]||(relative&&instruction[3]?location[key]||'':'');if(instruction[4])url[key]=url[key].toLowerCase()}
if(parser)url.query=parser(url.query);if(relative&&location.slashes&&url.pathname.charAt(0)!=='/'&&(url.pathname!==''||location.pathname!=='')){url.pathname=resolve(url.pathname,location.pathname)}
if(!required(url.port,url.protocol)){url.host=url.hostname;url.port=''}
url.username=url.password='';if(url.auth){instruction=url.auth.split(':');url.username=instruction[0]||'';url.password=instruction[1]||''}
url.origin=url.protocol&&url.host&&url.protocol!=='file:'?url.protocol+'//'+url.host:'null';url.href=url.toString()}
function set(part,value,fn){var url=this;switch(part){case 'query':if('string'===typeof value&&value.length){value=(fn||qs.parse)(value)}
url[part]=value;break;case 'port':url[part]=value;if(!required(value,url.protocol)){url.host=url.hostname;url[part]=''}else if(value){url.host=url.hostname+':'+value}
break;case 'hostname':url[part]=value;if(url.port)value+=':'+url.port;url.host=value;break;case 'host':url[part]=value;if(/:\d+$/.test(value)){value=value.split(':');url.port=value.pop();url.hostname=value.join(':')}else{url.hostname=value;url.port=''}
break;case 'protocol':url.protocol=value.toLowerCase();url.slashes=!fn;break;case 'pathname':case 'hash':if(value){var char=part==='pathname'?'/':'#';url[part]=value.charAt(0)!==char?char+value:value}else{url[part]=value}
break;default:url[part]=value}
for(var i=0;i<rules.length;i++){var ins=rules[i];if(ins[4])url[ins[1]]=url[ins[1]].toLowerCase()}
url.origin=url.protocol&&url.host&&url.protocol!=='file:'?url.protocol+'//'+url.host:'null';url.href=url.toString();return url}
function toString(stringify){if(!stringify||'function'!==typeof stringify)stringify=qs.stringify;var query,url=this,protocol=url.protocol;if(protocol&&protocol.charAt(protocol.length-1)!==':')protocol+=':';var result=protocol+(url.slashes?'//':'');if(url.username){result+=url.username;if(url.password)result+=':'+url.password;result+='@'}
result+=url.host+url.pathname;query='object'===typeof url.query?stringify(url.query):url.query;if(query)result+='?'!==query.charAt(0)?'?'+query:query;if(url.hash)result+=url.hash;return result}
URL.prototype={set:set,toString:toString};URL.extractProtocol=extractProtocol;URL.location=lolcation;URL.qs=qs;module.exports=URL}).call(this,typeof global!=="undefined"?global:typeof self!=="undefined"?self:typeof window!=="undefined"?window:{})},{"querystringify":7,"requires-port":10}],13:[function(_dereq_,module,exports){'use strict';var alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_'.split(''),length=64,map={},seed=0,i=0,prev;function encode(num){var encoded='';do{encoded=alphabet[num%length]+encoded;num=Math.floor(num/length)}while(num>0);return encoded}
function decode(str){var decoded=0;for(i=0;i<str.length;i++){decoded=decoded*length+map[str.charAt(i)]}
return decoded}
function yeast(){var now=encode(+new Date());if(now!==prev)return seed=0,prev=now;return now+'.'+encode(seed++)}
for(;i<length;i++)map[alphabet[i]]=i;yeast.encode=encode;yeast.decode=decode;module.exports=yeast},{}],14:[function(_dereq_,module,exports){'use strict';var EventEmitter=_dereq_('eventemitter3'),TickTock=_dereq_('tick-tock'),Recovery=_dereq_('recovery'),qs=_dereq_('querystringify'),inherits=_dereq_('inherits'),destroy=_dereq_('demolish'),yeast=_dereq_('yeast'),u2028=/\u2028/g,u2029=/\u2029/g;function context(self,method){if(self instanceof Primus)return;var failure=new Error('Primus#'+method+'\'s context should called with a Primus instance');if('function'!==typeof self.listeners||!self.listeners('error').length){throw failure}
self.emit('error',failure)}
var defaultUrl;try{if(location.origin){defaultUrl=location.origin}else{defaultUrl=location.protocol+'//'+location.host}}catch(e){defaultUrl='http://127.0.0.1'}
function Primus(url,options){if(!(this instanceof Primus))return new Primus(url,options);Primus.Stream.call(this);if('function'!==typeof this.client){return this.critical(new Error('The client library has not been compiled correctly, see '+'https://github.com/primus/primus#client-library for more details'))}
if('object'===typeof url){options=url;url=options.url||options.uri||defaultUrl}else{options=options||{}}
if('ping' in options||'pong' in options){return this.critical(new Error('The `ping` and `pong` options have been removed'))}
var primus=this;options.queueSize='queueSize' in options?options.queueSize:Infinity;options.timeout='timeout' in options?options.timeout:10e3;options.reconnect='reconnect' in options?options.reconnect:{};options.pingTimeout='pingTimeout' in options?options.pingTimeout:15000;options.strategy='strategy' in options?options.strategy:[];options.transport='transport' in options?options.transport:{};primus.buffer=[];primus.writable=!0;primus.readable=!0;primus.url=primus.parse(url||defaultUrl);primus.readyState=Primus.CLOSED;primus.options=options;primus.timers=new TickTock(this);primus.socket=null;primus.disconnect=!1;primus.transport=options.transport;primus.transformers={outgoing:[],incoming:[]};primus.recovery=new Recovery(options.reconnect);if('string'===typeof options.strategy){options.strategy=options.strategy.split(/\s?,\s?/g)}
if(!1===options.strategy){options.strategy=[]}else if(!options.strategy.length){options.strategy.push('disconnect','online');if(!this.authorization)options.strategy.push('timeout')}
options.strategy=options.strategy.join(',').toLowerCase();if('websockets' in options){primus.AVOID_WEBSOCKETS=!options.websockets}
if('network' in options){primus.NETWORK_EVENTS=options.network}
if(!options.manual)primus.timers.setTimeout('open',function open(){primus.timers.clear('open');primus.open()},0);primus.initialise(options)}
Primus.requires=Primus.require=function requires(name){if('function'!==typeof _dereq_)return undefined;return!('function'===typeof define&&define.amd)?_dereq_(name):undefined};try{Primus.Stream=Primus.requires('stream')}catch(e){}
if(!Primus.Stream)Primus.Stream=EventEmitter;inherits(Primus,Primus.Stream);Primus.OPENING=1;Primus.CLOSED=2;Primus.OPEN=3;Primus.prototype.AVOID_WEBSOCKETS=!1;Primus.prototype.NETWORK_EVENTS=!1;Primus.prototype.online=!0;try{if(Primus.prototype.NETWORK_EVENTS='onLine' in navigator&&(window.addEventListener||document.body.attachEvent)){if(!navigator.onLine){Primus.prototype.online=!1}}}catch(e){}
Primus.prototype.ark={};Primus.prototype.emits=_dereq_('emits');Primus.prototype.plugin=function plugin(name){context(this,'plugin');if(name)return this.ark[name];var plugins={};for(name in this.ark){plugins[name]=this.ark[name]}
return plugins};Primus.prototype.reserved=function reserved(evt){return(/^(incoming|outgoing)::/).test(evt)||evt in this.reserved.events};Primus.prototype.reserved.events={'reconnect scheduled':1,'reconnect timeout':1,'readyStateChange':1,'reconnect failed':1,'reconnected':1,'reconnect':1,'offline':1,'timeout':1,'destroy':1,'online':1,'error':1,'close':1,'open':1,'data':1,'end':1};Primus.prototype.initialise=function initialise(options){var primus=this;primus.recovery.on('reconnected',primus.emits('reconnected')).on('reconnect failed',primus.emits('reconnect failed',function failed(next){primus.emit('end');next()})).on('reconnect timeout',primus.emits('reconnect timeout')).on('reconnect scheduled',primus.emits('reconnect scheduled')).on('reconnect',primus.emits('reconnect',function reconnect(next){primus.emit('outgoing::reconnect');next()}));primus.on('outgoing::open',function opening(){var readyState=primus.readyState;primus.readyState=Primus.OPENING;if(readyState!==primus.readyState){primus.emit('readyStateChange','opening')}});primus.on('incoming::open',function opened(){var readyState=primus.readyState;if(primus.recovery.reconnecting()){primus.recovery.reconnected()}
primus.writable=!0;primus.readable=!0;if(!primus.online){primus.online=!0;primus.emit('online')}
primus.readyState=Primus.OPEN;if(readyState!==primus.readyState){primus.emit('readyStateChange','open')}
primus.heartbeat();if(primus.buffer.length){var data=primus.buffer.slice(),length=data.length,i=0;primus.buffer.length=0;for(;i<length;i++){primus._write(data[i])}}
primus.emit('open')});primus.on('incoming::ping',function ping(time){primus.online=!0;primus.heartbeat();primus.emit('outgoing::pong',time);primus._write('primus::pong::'+time)});primus.on('incoming::error',function error(e){var connect=primus.timers.active('connect'),err=e;if('string'===typeof e){err=new Error(e)}else if(!(e instanceof Error)&&'object'===typeof e){err=new Error(e.message||e.reason);for(var key in e){if(Object.prototype.hasOwnProperty.call(e,key))
err[key]=e[key]}}
if(primus.recovery.reconnecting())return primus.recovery.reconnected(err);if(primus.listeners('error').length)primus.emit('error',err);if(connect){if(~primus.options.strategy.indexOf('timeout')){primus.recovery.reconnect()}else{primus.end()}}});primus.on('incoming::data',function message(raw){primus.decoder(raw,function decoding(err,data){if(err)return primus.listeners('error').length&&primus.emit('error',err);if(primus.protocol(data))return;primus.transforms(primus,primus,'incoming',data,raw)})});primus.on('incoming::end',function end(){var readyState=primus.readyState;if(primus.disconnect){primus.disconnect=!1;return primus.end()}
primus.readyState=Primus.CLOSED;if(readyState!==primus.readyState){primus.emit('readyStateChange','end')}
if(primus.timers.active('connect'))primus.end();if(readyState!==Primus.OPEN){return primus.recovery.reconnecting()?primus.recovery.reconnect():!1}
this.writable=!1;this.readable=!1;this.timers.clear();primus.emit('close');if(~primus.options.strategy.indexOf('disconnect')){return primus.recovery.reconnect()}
primus.emit('outgoing::end');primus.emit('end')});primus.client();for(var plugin in primus.ark){primus.ark[plugin].call(primus,primus,options)}
if(!primus.NETWORK_EVENTS)return primus;primus.offlineHandler=function offline(){if(!primus.online)return;primus.online=!1;primus.emit('offline');primus.end();primus.recovery.reset()};primus.onlineHandler=function online(){if(primus.online)return;primus.online=!0;primus.emit('online');if(~primus.options.strategy.indexOf('online')){primus.recovery.reconnect()}};if(window.addEventListener){window.addEventListener('offline',primus.offlineHandler,!1);window.addEventListener('online',primus.onlineHandler,!1)}else if(document.body.attachEvent){document.body.attachEvent('onoffline',primus.offlineHandler);document.body.attachEvent('ononline',primus.onlineHandler)}
return primus};Primus.prototype.protocol=function protocol(msg){if('string'!==typeof msg||msg.indexOf('primus::')!==0)return!1;var last=msg.indexOf(':',8),value=msg.slice(last+2);switch(msg.slice(8,last)){case 'ping':this.emit('incoming::ping',+value);break;case 'server':if('close'===value){this.disconnect=!0}
break;case 'id':this.emit('incoming::id',value);break;default:return!1}
return!0};Primus.prototype.transforms=function transforms(primus,connection,type,data,raw){var packet={data:data},fns=primus.transformers[type];(function transform(index,done){var transformer=fns[index++];if(!transformer)return done();if(1===transformer.length){if(!1===transformer.call(connection,packet)){return}
return transform(index,done)}
transformer.call(connection,packet,function finished(err,arg){if(err)return connection.emit('error',err);if(!1===arg)return;transform(index,done)})}(0,function done(){if('incoming'===type)return connection.emit('data',packet.data,raw);connection._write(packet.data)}));return this};Primus.prototype.id=function id(fn){if(this.socket&&this.socket.id)return fn(this.socket.id);this._write('primus::id::');return this.once('incoming::id',fn)};Primus.prototype.open=function open(){context(this,'open');if(!this.recovery.reconnecting()&&this.options.timeout)this.timeout();this.emit('outgoing::open');return this};Primus.prototype.write=function write(data){context(this,'write');this.transforms(this,this,'outgoing',data);return!0};Primus.prototype._write=function write(data){var primus=this;if(Primus.OPEN!==primus.readyState){if(this.buffer.length===this.options.queueSize){this.buffer.splice(0,1)}
this.buffer.push(data);return!1}
primus.encoder(data,function encoded(err,packet){if(err)return primus.listeners('error').length&&primus.emit('error',err);if('string'===typeof packet){if(~packet.indexOf('\u2028'))packet=packet.replace(u2028,'\\u2028');if(~packet.indexOf('\u2029'))packet=packet.replace(u2029,'\\u2029')}
primus.emit('outgoing::data',packet)});return!0};Primus.prototype.heartbeat=function heartbeat(){if(!this.options.pingTimeout)return this;this.timers.clear('heartbeat');this.timers.setTimeout('heartbeat',function expired(){if(!this.online)return;this.online=!1;this.emit('offline');this.emit('incoming::end')},this.options.pingTimeout);return this};Primus.prototype.timeout=function timeout(){var primus=this;function remove(){primus.removeListener('error',remove).removeListener('open',remove).removeListener('end',remove).timers.clear('connect')}
primus.timers.setTimeout('connect',function expired(){remove();if(primus.readyState===Primus.OPEN||primus.recovery.reconnecting()){return}
primus.emit('timeout');if(~primus.options.strategy.indexOf('timeout')){primus.recovery.reconnect()}else{primus.end()}},primus.options.timeout);return primus.on('error',remove).on('open',remove).on('end',remove)};Primus.prototype.end=function end(data){context(this,'end');if(this.readyState===Primus.CLOSED&&!this.timers.active('connect')&&!this.timers.active('open')){if(this.recovery.reconnecting()){this.recovery.reset();this.emit('end')}
return this}
if(data!==undefined)this.write(data);this.writable=!1;this.readable=!1;var readyState=this.readyState;this.readyState=Primus.CLOSED;if(readyState!==this.readyState){this.emit('readyStateChange','end')}
this.timers.clear();this.emit('outgoing::end');this.emit('close');this.emit('end');return this};Primus.prototype.destroy=destroy('url timers options recovery socket transport transformers',{before:'end',after:['removeAllListeners',function detach(){if(!this.NETWORK_EVENTS)return;if(window.addEventListener){window.removeEventListener('offline',this.offlineHandler);window.removeEventListener('online',this.onlineHandler)}else if(document.body.attachEvent){document.body.detachEvent('onoffline',this.offlineHandler);document.body.detachEvent('ononline',this.onlineHandler)}}]});Primus.prototype.clone=function clone(obj){return this.merge({},obj)};Primus.prototype.merge=function merge(target){for(var i=1,key,obj;i<arguments.length;i++){obj=arguments[i];for(key in obj){if(Object.prototype.hasOwnProperty.call(obj,key))
target[key]=obj[key]}}
return target};Primus.prototype.parse=_dereq_('url-parse');Primus.prototype.querystring=qs.parse;Primus.prototype.querystringify=qs.stringify;Primus.prototype.uri=function uri(options){var url=this.url,server=[],qsa=!1;if(options.query)qsa=!0;options=options||{};options.protocol='protocol' in options?options.protocol:'http:';options.query=url.query&&qsa?url.query.slice(1):!1;options.secure='secure' in options?options.secure:url.protocol==='https:'||url.protocol==='wss:';options.auth='auth' in options?options.auth:url.auth;options.pathname='pathname' in options?options.pathname:this.pathname;options.port='port' in options?+options.port:+url.port||(options.secure?443:80);var querystring=this.querystring(options.query||'');querystring._primuscb=yeast();options.query=this.querystringify(querystring);this.emit('outgoing::url',options);server.push(options.secure?options.protocol.replace(':','s:'):options.protocol,'');server.push(options.auth?options.auth+'@'+url.host:url.host);if(options.pathname)server.push(options.pathname.slice(1));if(qsa)server[server.length-1]+='?'+options.query;else delete options.query;if(options.object)return options;return server.join('/')};Primus.prototype.transform=function transform(type,fn){context(this,'transform');if(!(type in this.transformers)){return this.critical(new Error('Invalid transformer type'))}
this.transformers[type].push(fn);return this};Primus.prototype.critical=function critical(err){if(this.emit('error',err))return this;throw err};Primus.connect=function connect(url,options){return new Primus(url,options)};Primus.EventEmitter=EventEmitter;Primus.prototype.client=function client(){var primus=this,socket;var Factory=(function factory(){if('undefined'!==typeof WebSocket)return WebSocket;if('undefined'!==typeof MozWebSocket)return MozWebSocket;try{return Primus.requires('ws')}
catch(e){}
return undefined})();if(!Factory)return primus.critical(new Error('Missing required `ws` module. Please run `npm install --save ws`'));primus.on('outgoing::open',function opening(){primus.emit('outgoing::end');try{var options={protocol:primus.url.protocol==='ws+unix:'?'ws+unix:':'ws:',query:!0};if(Factory.length===3){if('ws+unix:'===options.protocol){options.pathname=primus.url.pathname+':'+primus.pathname}
primus.socket=socket=new Factory(primus.uri(options),[],primus.transport)}else{primus.socket=socket=new Factory(primus.uri(options));socket.binaryType='arraybuffer'}}catch(e){return primus.emit('error',e)}
socket.onopen=primus.emits('incoming::open');socket.onerror=primus.emits('incoming::error');socket.onclose=primus.emits('incoming::end');socket.onmessage=primus.emits('incoming::data',function parse(next,evt){next(undefined,evt.data)})});primus.on('outgoing::data',function write(message){if(!socket||socket.readyState!==Factory.OPEN)return;try{socket.send(message)}
catch(e){primus.emit('incoming::error',e)}});primus.on('outgoing::reconnect',function reconnect(){primus.emit('outgoing::open')});primus.on('outgoing::end',function close(){if(!socket)return;socket.onerror=socket.onopen=socket.onclose=socket.onmessage=function(){};socket.close();socket=null})};Primus.prototype.authorization=!1;Primus.prototype.pathname="/primus";Primus.prototype.encoder=function encoder(data,fn){var err;try{data=BinaryPack.pack(data)}
catch(e){err=e}
fn(err,data)};Primus.prototype.decoder=function decoder(data,fn){var err;try{data=BinaryPack.unpack(data)}
catch(e){err=e}
fn(err,data)};Primus.prototype.version="7.2.2";if('undefined'!==typeof document&&'undefined'!==typeof navigator){if(document.addEventListener){document.addEventListener('keydown',function keydown(e){if(e.keyCode!==27||!e.preventDefault)return;e.preventDefault()},!1)}
var ua=(navigator.userAgent||'').toLowerCase(),parsed=ua.match(/.+(?:rv|it|ra|ie)[/: ](\d+)\.(\d+)(?:\.(\d+))?/)||[],version=+[parsed[1],parsed[2]].join('.');if(!~ua.indexOf('chrome')&&~ua.indexOf('safari')&&version<534.54){Primus.prototype.AVOID_WEBSOCKETS=!0}}
module.exports=Primus},{"demolish":1,"emits":2,"eventemitter3":3,"inherits":4,"querystringify":7,"recovery":8,"tick-tock":11,"url-parse":12,"yeast":13}]},{},[14])(14);var BinaryPack=(function(){var exports,bp;try{bp=Primus.requires('binary-pack')}
catch(e){}
if(bp)return bp;exports={};(function(){(function(context){(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(_dereq_,module,exports){var BufferBuilder=_dereq_('./bufferbuilder').BufferBuilder;var binaryFeatures=_dereq_('./bufferbuilder').binaryFeatures;var BinaryPack={unpack:function(data){var unpacker=new Unpacker(data);return unpacker.unpack()},pack:function(data){var packer=new Packer();packer.pack(data);var buffer=packer.getBuffer();return buffer}};module.exports=BinaryPack;function Unpacker(data){this.index=0;this.dataBuffer=data;this.dataView=new Uint8Array(this.dataBuffer);this.length=this.dataBuffer.byteLength}
Unpacker.prototype.unpack=function(){var type=this.unpack_uint8();if(type<0x80){var positive_fixnum=type;return positive_fixnum}else if((type^0xe0)<0x20){var negative_fixnum=(type^0xe0)-0x20;return negative_fixnum}
var size;if((size=type^0xa0)<=0x0f){return this.unpack_raw(size)}else if((size=type^0xb0)<=0x0f){return this.unpack_string(size)}else if((size=type^0x90)<=0x0f){return this.unpack_array(size)}else if((size=type^0x80)<=0x0f){return this.unpack_map(size)}
switch(type){case 0xc0:return null;case 0xc1:return undefined;case 0xc2:return!1;case 0xc3:return!0;case 0xca:return this.unpack_float();case 0xcb:return this.unpack_double();case 0xcc:return this.unpack_uint8();case 0xcd:return this.unpack_uint16();case 0xce:return this.unpack_uint32();case 0xcf:return this.unpack_uint64();case 0xd0:return this.unpack_int8();case 0xd1:return this.unpack_int16();case 0xd2:return this.unpack_int32();case 0xd3:return this.unpack_int64();case 0xd4:return undefined;case 0xd5:return undefined;case 0xd6:return undefined;case 0xd7:return undefined;case 0xd8:size=this.unpack_uint16();return this.unpack_string(size);case 0xd9:size=this.unpack_uint32();return this.unpack_string(size);case 0xda:size=this.unpack_uint16();return this.unpack_raw(size);case 0xdb:size=this.unpack_uint32();return this.unpack_raw(size);case 0xdc:size=this.unpack_uint16();return this.unpack_array(size);case 0xdd:size=this.unpack_uint32();return this.unpack_array(size);case 0xde:size=this.unpack_uint16();return this.unpack_map(size);case 0xdf:size=this.unpack_uint32();return this.unpack_map(size)}}
Unpacker.prototype.unpack_uint8=function(){var byte=this.dataView[this.index]&0xff;this.index++;return byte};Unpacker.prototype.unpack_uint16=function(){var bytes=this.read(2);var uint16=((bytes[0]&0xff)*256)+(bytes[1]&0xff);this.index+=2;return uint16}
Unpacker.prototype.unpack_uint32=function(){var bytes=this.read(4);var uint32=((bytes[0]*256+bytes[1])*256+bytes[2])*256+bytes[3];this.index+=4;return uint32}
Unpacker.prototype.unpack_uint64=function(){var bytes=this.read(8);var uint64=((((((bytes[0]*256+bytes[1])*256+bytes[2])*256+bytes[3])*256+bytes[4])*256+bytes[5])*256+bytes[6])*256+bytes[7];this.index+=8;return uint64}
Unpacker.prototype.unpack_int8=function(){var uint8=this.unpack_uint8();return(uint8<0x80)?uint8:uint8-(1<<8)};Unpacker.prototype.unpack_int16=function(){var uint16=this.unpack_uint16();return(uint16<0x8000)?uint16:uint16-(1<<16)}
Unpacker.prototype.unpack_int32=function(){var uint32=this.unpack_uint32();return(uint32<Math.pow(2,31))?uint32:uint32-Math.pow(2,32)}
Unpacker.prototype.unpack_int64=function(){var uint64=this.unpack_uint64();return(uint64<Math.pow(2,63))?uint64:uint64-Math.pow(2,64)}
Unpacker.prototype.unpack_raw=function(size){if(this.length<this.index+size){throw new Error('BinaryPackFailure: index is out of range'+' '+this.index+' '+size+' '+this.length)}
var buf=this.dataBuffer.slice(this.index,this.index+size);this.index+=size;return buf}
Unpacker.prototype.unpack_string=function(size){var bytes=this.read(size);var i=0,str='',c,code;while(i<size){c=bytes[i];if(c<128){str+=String.fromCharCode(c);i++}else if((c^0xc0)<32){code=((c^0xc0)<<6)|(bytes[i+1]&63);str+=String.fromCharCode(code);i+=2}else{code=((c&15)<<12)|((bytes[i+1]&63)<<6)|(bytes[i+2]&63);str+=String.fromCharCode(code);i+=3}}
this.index+=size;return str}
Unpacker.prototype.unpack_array=function(size){var objects=new Array(size);for(var i=0;i<size;i++){objects[i]=this.unpack()}
return objects}
Unpacker.prototype.unpack_map=function(size){var map={};for(var i=0;i<size;i++){var key=this.unpack();var value=this.unpack();map[key]=value}
return map}
Unpacker.prototype.unpack_float=function(){var uint32=this.unpack_uint32();var sign=uint32>>31;var exp=((uint32>>23)&0xff)-127;var fraction=(uint32&0x7fffff)|0x800000;return(sign==0?1:-1)*fraction*Math.pow(2,exp-23)}
Unpacker.prototype.unpack_double=function(){var h32=this.unpack_uint32();var l32=this.unpack_uint32();var sign=h32>>31;var exp=((h32>>20)&0x7ff)-1023;var hfrac=(h32&0xfffff)|0x100000;var frac=hfrac*Math.pow(2,exp-20)+l32*Math.pow(2,exp-52);return(sign==0?1:-1)*frac}
Unpacker.prototype.read=function(length){var j=this.index;if(j+length<=this.length){return this.dataView.subarray(j,j+length)}else{throw new Error('BinaryPackFailure: read index out of range')}}
function Packer(){this.bufferBuilder=new BufferBuilder()}
Packer.prototype.getBuffer=function(){return this.bufferBuilder.getBuffer()}
Packer.prototype.pack=function(value){var type=typeof(value);if(type=='string'){this.pack_string(value)}else if(type=='number'){if(Math.floor(value)===value){this.pack_integer(value)}else{this.pack_double(value)}}else if(type=='boolean'){if(value===!0){this.bufferBuilder.append(0xc3)}else if(value===!1){this.bufferBuilder.append(0xc2)}}else if(type=='undefined'){this.bufferBuilder.append(0xc0)}else if(type=='object'){if(value===null){this.bufferBuilder.append(0xc0)}else{var constructor=value.constructor;if(constructor==Array){this.pack_array(value)}else if(constructor==Blob||constructor==File){this.pack_bin(value)}else if(constructor==ArrayBuffer){if(binaryFeatures.useArrayBufferView){this.pack_bin(new Uint8Array(value))}else{this.pack_bin(value)}}else if('BYTES_PER_ELEMENT' in value){if(binaryFeatures.useArrayBufferView){this.pack_bin(new Uint8Array(value.buffer))}else{this.pack_bin(value.buffer)}}else if(constructor==Object){this.pack_object(value)}else if(constructor==Date){this.pack_string(value.toString())}else if(typeof value.toBinaryPack=='function'){this.bufferBuilder.append(value.toBinaryPack())}else{throw new Error('Type "'+constructor.toString()+'" not yet supported')}}}else{throw new Error('Type "'+type+'" not yet supported')}
this.bufferBuilder.flush()}
Packer.prototype.pack_bin=function(blob){var length=blob.length||blob.byteLength||blob.size;if(length<=0x0f){this.pack_uint8(0xa0+length)}else if(length<=0xffff){this.bufferBuilder.append(0xda);this.pack_uint16(length)}else if(length<=0xffffffff){this.bufferBuilder.append(0xdb);this.pack_uint32(length)}else{throw new Error('Invalid length')}
this.bufferBuilder.append(blob)}
Packer.prototype.pack_string=function(str){var length=utf8Length(str);if(length<=0x0f){this.pack_uint8(0xb0+length)}else if(length<=0xffff){this.bufferBuilder.append(0xd8);this.pack_uint16(length)}else if(length<=0xffffffff){this.bufferBuilder.append(0xd9);this.pack_uint32(length)}else{throw new Error('Invalid length')}
this.bufferBuilder.append(str)}
Packer.prototype.pack_array=function(ary){var length=ary.length;if(length<=0x0f){this.pack_uint8(0x90+length)}else if(length<=0xffff){this.bufferBuilder.append(0xdc)
this.pack_uint16(length)}else if(length<=0xffffffff){this.bufferBuilder.append(0xdd);this.pack_uint32(length)}else{throw new Error('Invalid length')}
for(var i=0;i<length;i++){this.pack(ary[i])}}
Packer.prototype.pack_integer=function(num){if(-0x20<=num&&num<=0x7f){this.bufferBuilder.append(num&0xff)}else if(0x00<=num&&num<=0xff){this.bufferBuilder.append(0xcc);this.pack_uint8(num)}else if(-0x80<=num&&num<=0x7f){this.bufferBuilder.append(0xd0);this.pack_int8(num)}else if(0x0000<=num&&num<=0xffff){this.bufferBuilder.append(0xcd);this.pack_uint16(num)}else if(-0x8000<=num&&num<=0x7fff){this.bufferBuilder.append(0xd1);this.pack_int16(num)}else if(0x00000000<=num&&num<=0xffffffff){this.bufferBuilder.append(0xce);this.pack_uint32(num)}else if(-0x80000000<=num&&num<=0x7fffffff){this.bufferBuilder.append(0xd2);this.pack_int32(num)}else if(-0x8000000000000000<=num&&num<=0x7FFFFFFFFFFFFFFF){this.bufferBuilder.append(0xd3);this.pack_int64(num)}else if(0x0000000000000000<=num&&num<=0xFFFFFFFFFFFFFFFF){this.bufferBuilder.append(0xcf);this.pack_uint64(num)}else{throw new Error('Invalid integer')}}
Packer.prototype.pack_double=function(num){var sign=0;if(num<0){sign=1;num=-num}
var exp=Math.floor(Math.log(num)/Math.LN2);var frac0=num/Math.pow(2,exp)-1;var frac1=Math.floor(frac0*Math.pow(2,52));var b32=Math.pow(2,32);var h32=(sign<<31)|((exp+1023)<<20)|(frac1/b32)&0x0fffff;var l32=frac1%b32;this.bufferBuilder.append(0xcb);this.pack_int32(h32);this.pack_int32(l32)}
Packer.prototype.pack_object=function(obj){var keys=Object.keys(obj);var length=keys.length;if(length<=0x0f){this.pack_uint8(0x80+length)}else if(length<=0xffff){this.bufferBuilder.append(0xde);this.pack_uint16(length)}else if(length<=0xffffffff){this.bufferBuilder.append(0xdf);this.pack_uint32(length)}else{throw new Error('Invalid length')}
for(var prop in obj){if(obj.hasOwnProperty(prop)){this.pack(prop);this.pack(obj[prop])}}}
Packer.prototype.pack_uint8=function(num){this.bufferBuilder.append(num)}
Packer.prototype.pack_uint16=function(num){this.bufferBuilder.append(num>>8);this.bufferBuilder.append(num&0xff)}
Packer.prototype.pack_uint32=function(num){var n=num&0xffffffff;this.bufferBuilder.append((n&0xff000000)>>>24);this.bufferBuilder.append((n&0x00ff0000)>>>16);this.bufferBuilder.append((n&0x0000ff00)>>>8);this.bufferBuilder.append((n&0x000000ff))}
Packer.prototype.pack_uint64=function(num){var high=num/Math.pow(2,32);var low=num%Math.pow(2,32);this.bufferBuilder.append((high&0xff000000)>>>24);this.bufferBuilder.append((high&0x00ff0000)>>>16);this.bufferBuilder.append((high&0x0000ff00)>>>8);this.bufferBuilder.append((high&0x000000ff));this.bufferBuilder.append((low&0xff000000)>>>24);this.bufferBuilder.append((low&0x00ff0000)>>>16);this.bufferBuilder.append((low&0x0000ff00)>>>8);this.bufferBuilder.append((low&0x000000ff))}
Packer.prototype.pack_int8=function(num){this.bufferBuilder.append(num&0xff)}
Packer.prototype.pack_int16=function(num){this.bufferBuilder.append((num&0xff00)>>8);this.bufferBuilder.append(num&0xff)}
Packer.prototype.pack_int32=function(num){this.bufferBuilder.append((num>>>24)&0xff);this.bufferBuilder.append((num&0x00ff0000)>>>16);this.bufferBuilder.append((num&0x0000ff00)>>>8);this.bufferBuilder.append((num&0x000000ff))}
Packer.prototype.pack_int64=function(num){var high=Math.floor(num/Math.pow(2,32));var low=num%Math.pow(2,32);this.bufferBuilder.append((high&0xff000000)>>>24);this.bufferBuilder.append((high&0x00ff0000)>>>16);this.bufferBuilder.append((high&0x0000ff00)>>>8);this.bufferBuilder.append((high&0x000000ff));this.bufferBuilder.append((low&0xff000000)>>>24);this.bufferBuilder.append((low&0x00ff0000)>>>16);this.bufferBuilder.append((low&0x0000ff00)>>>8);this.bufferBuilder.append((low&0x000000ff))}
function _utf8Replace(m){var code=m.charCodeAt(0);if(code<=0x7ff)return'00';if(code<=0xffff)return'000';if(code<=0x1fffff)return'0000';if(code<=0x3ffffff)return'00000';return'000000'}
function utf8Length(str){if(str.length>600){return(new Blob([str])).size}else{return str.replace(/[^\u0000-\u007F]/g,_utf8Replace).length}}},{"./bufferbuilder":2}],2:[function(_dereq_,module,exports){var binaryFeatures={};binaryFeatures.useBlobBuilder=(function(){try{new Blob([]);return!1}catch(e){return!0}})();binaryFeatures.useArrayBufferView=!binaryFeatures.useBlobBuilder&&(function(){try{return(new Blob([new Uint8Array([])])).size===0}catch(e){return!0}})();module.exports.binaryFeatures=binaryFeatures;var BlobBuilder=module.exports.BlobBuilder;if(typeof window!='undefined'){BlobBuilder=module.exports.BlobBuilder=window.WebKitBlobBuilder||window.MozBlobBuilder||window.MSBlobBuilder||window.BlobBuilder}
function BufferBuilder(){this._pieces=[];this._parts=[]}
BufferBuilder.prototype.append=function(data){if(typeof data==='number'){this._pieces.push(data)}else{this.flush();this._parts.push(data)}};BufferBuilder.prototype.flush=function(){if(this._pieces.length>0){var buf=new Uint8Array(this._pieces);if(!binaryFeatures.useArrayBufferView){buf=buf.buffer}
this._parts.push(buf);this._pieces=[]}};BufferBuilder.prototype.getBuffer=function(){this.flush();if(binaryFeatures.useBlobBuilder){var builder=new BlobBuilder();for(var i=0,ii=this._parts.length;i<ii;i++){builder.append(this._parts[i])}
return builder.getBlob()}else{return new Blob(this._parts)}};module.exports.BufferBuilder=BufferBuilder},{}],3:[function(_dereq_,module,exports){context.BinaryPack=_dereq_('js-binarypack')},{"js-binarypack":1}]},{},[3])})(this)}).call(exports);return exports.BinaryPack})();return Primus},[])